import React, { useEffect } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowUpRight, Check, ChevronRight, Clock3, Menu, MessageCircle, Sparkles, X, Zap } from 'lucide-react'
import './index.css'

const projects = [
  { name: 'Maximum Fitness', tag: 'Фитнес-клуб', description: 'Спортивный digital-опыт с расписанием и онлайн-записью.', tone: 'from-indigo-950 via-slate-900 to-violet-950', number: '01', art: 'MAX' },
  { name: 'DUET', tag: 'Ресторан', description: 'Элегантный сайт с меню, атмосферой и системой бронирования.', tone: 'from-stone-950 via-amber-950/40 to-stone-900', number: '02', art: 'DUET' },
  { name: 'LUMé', tag: 'Салон красоты', description: 'Светлый премиальный стиль, который превращает визит в запись.', tone: 'from-rose-950/60 via-stone-900 to-orange-950/40', number: '03', art: 'LUMé' },
]

const services = [
  ['01', 'Сайты для ресторанов / кафе', 'Покажем вашу атмосферу, меню и поможем гостю забронировать столик в пару кликов.', '✦'],
  ['02', 'Сайты для салонов красоты', 'Визуальная подача, прайс и удобная онлайн-запись без лишних звонков.', '◈'],
  ['03', 'Каталоги и интернет-магазины', 'Структурируем ассортимент и сделаем путь от интереса до покупки простым.', '▦'],
  ['04', 'Автоматизация заявок', 'Свяжем сайт с WhatsApp, Telegram или CRM, чтобы ни один клиент не потерялся.', '↗'],
]

const pricing = [
  ['Сайт-визитка', 'от 15 000 сом', ['До 5 блоков', 'Адаптивный дизайн', 'Форма заявки', 'Публикация на домене']],
  ['Сайт с автоматизацией', 'от 25 000 сом', ['Уникальный дизайн', 'WhatsApp / Telegram', 'Онлайн-запись', 'Подключение аналитики']],
  ['Каталог / магазин', 'от 40 000 сом', ['Каталог товаров', 'Корзина и заявки', 'Интеграции с CRM', 'Поддержка после запуска']],
]

function SocialIcon({ type }) {
  if (type === 'telegram') return <svg viewBox="0 0 24 24" fill="none" className="size-4" aria-hidden="true"><path d="m21.3 4.3-3.2 15.1c-.2 1.1-.8 1.4-1.7.9l-4.6-3.4-2.2 2.1c-.2.2-.4.4-.8.4l.3-4.7 8.5-7.7c.4-.3-.1-.5-.6-.2L6.5 13.4l-4.6-1.5c-1-.3-1-1 .2-1.4L20 3.9c.8-.3 1.5.2 1.3.4Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></svg>
  if (type === 'instagram') return <svg viewBox="0 0 24 24" fill="none" className="size-4" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" stroke="currentColor" strokeWidth="1.5"/><circle cx="12" cy="12" r="4" stroke="currentColor" strokeWidth="1.5"/><circle cx="17.2" cy="6.8" r="1" fill="currentColor"/></svg>
  return <svg viewBox="0 0 24 24" fill="none" className="size-4" aria-hidden="true"><path d="M20.1 3.9A10 10 0 0 0 4.4 16.1L3.5 20.5l4.5-.9A10 10 0 1 0 20.1 3.9Z" stroke="currentColor" strokeWidth="1.5"/><path d="M8.3 7.7c.2-.2.5-.2.7 0l1.2 1.5c.2.2.2.5 0 .7l-.7.8c.7 1.5 1.6 2.3 3.1 3.1l.8-.7c.2-.2.5-.2.7 0l1.5 1.2c.2.2.2.5 0 .7l-.5.6c-.4.5-1.1.7-1.7.5-3.3-1.1-5.7-3.5-6.8-6.8-.2-.6 0-1.3.5-1.7l.6-.5Z" fill="currentColor"/></svg>
}

function App() {
  const [menuOpen, setMenuOpen] = React.useState(false)
  useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(e => e.isIntersecting && e.target.classList.add('visible')), { threshold: .12 }); document.querySelectorAll('.reveal').forEach(el => observer.observe(el)); return () => observer.disconnect() }, [])
  const close = () => setMenuOpen(false)
  return <div className="overflow-hidden">
    <nav className="fixed top-0 z-50 w-full border-b border-white/[.06] bg-[#0a0a0f]/75 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><a href="#top" className="font-display text-xl font-bold tracking-[-.06em]">FOR<span className="gradient-text">MA.</span></a><div className="hidden items-center gap-8 text-sm text-zinc-400 md:flex"><a href="#projects" className="hover:text-white">Проекты</a><a href="#services" className="hover:text-white">Услуги</a><a href="#process" className="hover:text-white">Как работаем</a><a href="#contact" className="rounded-full border border-white/15 px-4 py-2 text-white transition hover:border-violet-400/60 hover:bg-white/5">Обсудить проект <ArrowUpRight className="ml-1 inline size-3" /></a></div><button onClick={() => setMenuOpen(!menuOpen)} className="md:hidden" aria-label="Открыть меню">{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <div className="border-t border-white/10 px-5 py-6 md:hidden"><div className="flex flex-col gap-5 text-zinc-300"><a onClick={close} href="#projects">Проекты</a><a onClick={close} href="#services">Услуги</a><a onClick={close} href="#process">Как работаем</a><a onClick={close} href="#contact">Обсудить проект →</a></div></div>}</nav>

    <main id="top"><section className="relative isolate flex min-h-[760px] items-center px-5 pt-28 lg:min-h-[850px] lg:px-8"><div className="grid-bg absolute inset-0 -z-10"/><div className="blob absolute -right-32 top-32 -z-10 size-[420px] rounded-full bg-violet-600/20 blur-[110px]"/><div className="absolute -left-40 bottom-20 -z-10 size-96 rounded-full bg-indigo-600/10 blur-[100px]"/><div className="mx-auto grid w-full max-w-7xl items-center gap-16 lg:grid-cols-[1.1fr_.9fr]"><div><div className="mb-7 flex items-center gap-2 text-sm text-violet-300"><span className="flex size-2 animate-pulse rounded-full bg-violet-400"/>Бишкек · доступен для новых проектов</div><h1 className="max-w-4xl font-display text-5xl font-semibold leading-[.98] tracking-[-.075em] sm:text-7xl lg:text-[6.7rem]">Сайты,<br/><span className="gradient-text">которые</span><br/>продают.</h1><p className="mt-8 max-w-lg text-lg leading-relaxed text-zinc-400">Создаю быстрые и стильные сайты для бизнеса — от первой идеи до публикации на вашем домене. С AI-инструментами и вниманием к деталям.</p><div className="mt-10 flex flex-wrap gap-3"><a href="#projects" className="group rounded-full bg-white px-6 py-3.5 font-medium text-black transition hover:bg-violet-100">Смотреть проекты <ArrowUpRight className="ml-2 inline size-4 transition group-hover:translate-x-1 group-hover:-translate-y-1"/></a><a href="https://wa.me/996555000000" className="rounded-full border border-white/15 px-6 py-3.5 font-medium text-white transition hover:border-white/40 hover:bg-white/5">Написать в WhatsApp</a></div></div><div className="relative hidden h-[420px] lg:block"><div className="glass absolute right-5 top-8 w-80 rotate-6 rounded-3xl p-4 shadow-2xl shadow-violet-950/40"><div className="mb-4 flex justify-between text-xs text-zinc-500"><span>PROJECT / 03</span><span>2024</span></div><div className="flex h-52 items-end rounded-2xl bg-gradient-to-br from-fuchsia-200 via-rose-300 to-orange-400 p-5"><span className="font-display text-4xl font-bold tracking-[-.08em] text-zinc-900">LUMé</span></div><div className="mt-4 flex justify-between text-sm"><span>Beauty studio</span><span className="text-zinc-500">↗</span></div></div><div className="glass absolute bottom-3 left-8 w-64 -rotate-6 rounded-3xl p-4 shadow-2xl shadow-indigo-950/50"><div className="mb-4 h-32 rounded-2xl bg-gradient-to-br from-indigo-500/60 to-violet-950 p-4"><div className="font-display text-2xl font-bold">MAXIMUM<span className="text-violet-300">.</span></div><div className="mt-14 text-[10px] uppercase tracking-[.3em] text-indigo-200">Train your limit</div></div><div className="flex items-center justify-between text-sm"><span>Fitness club</span><span className="text-zinc-500">01</span></div></div></div></div></section>

    <section className="reveal border-y border-white/[.07] bg-white/[.015] px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_1.2fr]"><div><p className="mb-5 text-sm uppercase tracking-[.2em] text-violet-300">Почему мы</p><h2 className="max-w-md font-display text-4xl font-semibold tracking-[-.06em] sm:text-5xl">Большой результат.<br/><span className="text-zinc-500">Без агентских накруток.</span></h2></div><div><p className="max-w-xl text-lg leading-relaxed text-zinc-400">Использую современные AI-инструменты, чтобы работать быстрее, но не жертвовать качеством. Вы получаете профессиональный сайт, который помогает бизнесу расти — без месяцев ожидания и сложных процессов.</p><div className="mt-10 grid grid-cols-3 gap-3"><div className="border-l border-violet-400 pl-4"><p className="font-display text-2xl font-semibold">2–3</p><p className="mt-1 text-xs text-zinc-500">недели на запуск</p></div><div className="border-l border-violet-400 pl-4"><p className="font-display text-2xl font-semibold">15k+</p><p className="mt-1 text-xs text-zinc-500">сом — старт</p></div><div className="border-l border-violet-400 pl-4"><p className="font-display text-2xl font-semibold">24/7</p><p className="mt-1 text-xs text-zinc-500">поддержка</p></div></div></div></div></section>

    <section id="projects" className="reveal mx-auto max-w-7xl px-5 py-28 lg:px-8"><div className="mb-12 flex items-end justify-between"><div><p className="mb-4 text-sm uppercase tracking-[.2em] text-violet-300">Избранные работы</p><h2 className="font-display text-4xl font-semibold tracking-[-.06em] sm:text-6xl">Проекты, которыми<br/><span className="text-zinc-500">хочется делиться.</span></h2></div><span className="hidden text-sm text-zinc-500 sm:block">01 — 03</span></div><div className="grid gap-5 md:grid-cols-3">{projects.map(p => <article key={p.name} className="card-hover glass group rounded-3xl p-3"><div className={`relative flex h-72 items-end overflow-hidden rounded-2xl bg-gradient-to-br ${p.tone} p-6`}><div className="absolute inset-0 opacity-20" style={{backgroundImage:'radial-gradient(circle at 70% 25%, white 0 1px, transparent 1px)', backgroundSize:'18px 18px'}}/><span className="relative font-display text-5xl font-bold tracking-[-.1em] text-white/90">{p.art}<sup className="text-sm">®</sup></span><span className="absolute right-5 top-5 text-xs text-white/50">{p.number}</span></div><div className="p-4 pb-3"><div className="flex items-center justify-between gap-2"><h3 className="font-display text-xl font-semibold">{p.name}</h3><span className="rounded-full bg-white/5 px-2.5 py-1 text-[10px] text-zinc-400">{p.tag}</span></div><p className="mt-3 text-sm leading-relaxed text-zinc-500">{p.description}</p><a href="#contact" className="mt-5 inline-flex items-center text-sm text-white transition group-hover:text-violet-300">Смотреть демо <ChevronRight className="ml-1 size-4"/></a></div></article>)}</div></section>

    <section id="services" className="reveal border-y border-white/[.07] bg-white/[.015] px-5 py-28 lg:px-8"><div className="mx-auto max-w-7xl"><p className="mb-4 text-sm uppercase tracking-[.2em] text-violet-300">Что я делаю</p><div className="mb-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><h2 className="font-display text-4xl font-semibold tracking-[-.06em] sm:text-6xl">Инструменты для<br/><span className="text-zinc-500">вашего роста.</span></h2><p className="max-w-xs text-sm leading-relaxed text-zinc-500">Сайт — это не просто красивая страница. Это ваш лучший менеджер по продажам.</p></div><div className="grid gap-3 sm:grid-cols-2">{services.map(([num,title,desc,icon]) => <div key={title} className="card-hover glass rounded-2xl p-6"><div className="flex items-start justify-between"><span className="font-mono text-xs text-violet-300">{num}</span><span className="font-display text-2xl text-violet-300">{icon}</span></div><h3 className="mt-12 font-display text-xl font-semibold">{title}</h3><p className="mt-3 max-w-md text-sm leading-relaxed text-zinc-500">{desc}</p></div>)}</div></div></section>

    <section id="process" className="reveal mx-auto max-w-7xl px-5 py-28 lg:px-8"><p className="mb-4 text-sm uppercase tracking-[.2em] text-violet-300">Простой процесс</p><h2 className="font-display text-4xl font-semibold tracking-[-.06em] sm:text-6xl">От идеи <span className="text-zinc-500">до запуска.</span></h2><div className="relative mt-16 grid gap-10 md:grid-cols-4 md:gap-5">{[['01','Знакомимся','Обсуждаем задачу, цели и стиль вашего бизнеса.'],['02','Собираю демо','Показываю первую версию в вашем стиле уже через несколько дней.'],['03','Шлифуем','Вносим правки и доводим каждую деталь до идеала.'],['04','Запускаем','Публикую сайт на вашем домене и всё настраиваю.']].map(([n,t,d],i)=><div key={n} className="relative"><div className="mb-5 flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-full border border-violet-400/60 bg-[#0a0a0f] font-mono text-xs text-violet-300">{n}</span>{i < 3 && <div className="hidden h-px flex-1 bg-gradient-to-r from-violet-400/50 to-transparent md:block"/>}</div><h3 className="font-display text-xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-relaxed text-zinc-500">{d}</p></div>)}</div></section>

    <section className="reveal border-y border-white/[.07] bg-white/[.015] px-5 py-28 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mb-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-4 text-sm uppercase tracking-[.2em] text-violet-300">Инвестиция в бизнес</p><h2 className="font-display text-4xl font-semibold tracking-[-.06em] sm:text-6xl">Выберите свой<br/><span className="text-zinc-500">следующий шаг.</span></h2></div><p className="max-w-xs text-sm leading-relaxed text-zinc-500">Финальная стоимость зависит от задачи. Обсудим ваш проект и подберём оптимальное решение.</p></div><div className="grid gap-3 lg:grid-cols-3">{pricing.map(([title,price,features],i)=><div key={title} className={`card-hover rounded-2xl border p-6 ${i === 1 ? 'border-violet-400/50 bg-violet-500/[.08]' : 'glass'}`}><div className="flex items-start justify-between"><h3 className="font-display text-xl font-semibold">{title}</h3>{i === 1 && <span className="rounded-full bg-violet-400/20 px-2 py-1 text-[10px] text-violet-200">популярный</span>}</div><p className="mt-8 font-display text-3xl font-semibold tracking-[-.05em]">{price}</p><ul className="mt-8 space-y-3 border-t border-white/10 pt-6">{features.map(f=><li key={f} className="flex items-center gap-2 text-sm text-zinc-400"><Check className="size-4 text-violet-300"/>{f}</li>)}</ul><a href="#contact" className="mt-8 block rounded-full border border-white/15 py-3 text-center text-sm transition hover:border-violet-300 hover:bg-white/5">Обсудить проект <ArrowUpRight className="ml-1 inline size-3"/></a></div>)}</div></div></section>

    <section id="contact" className="reveal relative isolate px-5 py-32 text-center lg:px-8"><div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_center,rgba(124,58,237,.2),transparent_60%)]"/><Sparkles className="mx-auto mb-7 size-7 text-violet-300"/><h2 className="mx-auto max-w-3xl font-display text-5xl font-semibold leading-none tracking-[-.07em] sm:text-7xl">Готовы обсудить<br/><span className="gradient-text">ваш проект?</span></h2><p className="mx-auto mt-7 max-w-md text-zinc-400">Расскажите, ��то хотите создать. Я отвечу в течение рабочего дня и предложу следующие шаги.</p><div className="mt-9 flex justify-center gap-3"><a href="https://wa.me/996555000000" className="rounded-full bg-white px-7 py-4 font-medium text-black transition hover:bg-violet-100"><MessageCircle className="mr-2 inline size-4"/>Написать в WhatsApp</a><a href="https://t.me/your_username" className="rounded-full border border-white/15 px-7 py-4 font-medium transition hover:border-white/40 hover:bg-white/5">Telegram <ArrowUpRight className="ml-1 inline size-4"/></a></div></section></main>

    <footer className="border-t border-white/[.07] px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><a href="#top" className="font-display text-xl font-bold tracking-[-.06em]">FOR<span className="gradient-text">MA.</span></a><p className="mt-2 text-xs text-zinc-600">Сайты с характером. Бишкек, Кыргызстан.</p></div><div className="flex items-center gap-3"><a aria-label="Instagram" href="#" className="rounded-full border border-white/10 p-2 text-zinc-400 transition hover:border-violet-400 hover:text-white"><SocialIcon type="instagram"/></a><a aria-label="Telegram" href="#" className="rounded-full border border-white/10 p-2 text-zinc-400 transition hover:border-violet-400 hover:text-white"><SocialIcon type="telegram"/></a><a aria-label="WhatsApp" href="#" className="rounded-full border border-white/10 p-2 text-zinc-400 transition hover:border-violet-400 hover:text-white"><SocialIcon type="whatsapp"/></a><span className="ml-3 text-xs text-zinc-600">© 2024 FORMA</span></div></div></footer>
  </div>
}

createRoot(document.getElementById('root')).render(<App />)
